### PR TITLE
Apply unique parent package transform across all path elements

### PR DESCRIPTION
**Pull request by lread**
Formerly we were applying this transform against individual
path elements which allowed for the possibility of packages
parent and parent.child to be included.

I also decided to sort registered packages for repeatability.
We always start with clojure, but the remaining packages are
sorted by name.

To express this package scenario, I decided to re-org our
integration tests. Our hello world app has moved from under
test/ to the new test-hello-world/.
This new setup should somewhat more reflect realworld usages.

### CODE REVIEW

**Comment by lread** [comment]
Note: did have failure on Windows, hence the ci commits.
Don't understand why things failed on Windows. 
Guessing either deps download wonkiness or gha wonkiness.

**Comment by borkdude** [comment]
@lread I think the error you saw in CI was related to:

> No such var: reader/read

and this relates to the first line workaround we have in `build.clj`.

**Comment by borkdude** [comment]
So you should really copy that line to your new build.clj to prevent such errors.

**Comment by lread** [comment]
Aha, did not notice that! Thanks, will do!

**Comment by borkdude** [comment]
Can we please not use force-pushes in this organization? It's very hard for me to see what is the delta compared to my previous review.

**Comment by lread** [comment]
I don't do force pushes after a pull request is created.
Should I not be doing them before I create a pull request either?

**Comment by borkdude** [comment]
Whoops, I misread, sorry.

**Comment by lread** [comment]
No problemo!

**Comment by lread** [comment]
That's a nasty tools.build issue, mysterious to diagnose the cause unless you are familiar with the symptom!

**Pull request merged**
